### ISSUE TITLE
Fix removal of quotes from property names

### ISSUE THREAD

**Issue by k-dauda** [ember-cli/ember-cli-babili#10]
See: https://github.com/babel/babili/pull/543/files

**Comment by kanongil** [comment]
@rwjblue You need to update the `babel-preset-babili` dependency in [broccoli-babili](https://github.com/ember-cli/broccoli-babili/blob/master/package.json) to fix this.

**Comment by rwjblue** [comment]
Updated, and released as 0.2.0.

Thank you!

**Comment by k-dauda** [comment]
@rwjblue tried v0.2.0 and the problem still occurs, will open up the issue with the babili repo
